FROM debian:buster-slim

RUN apt update && apt -y install curl uglifyjs gcc git nodejs npm && npm install npm@latest -g

WORKDIR /build
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

COPY . .

RUN git clone https://github.com/bauhaus93/wishlist-elm frontend

RUN cd frontend && npm install &&  git pull --ff-only && npm run build

RUN PATH=$PATH:$HOME/.cargo/bin scripts/build.sh

